workflows:
  ios-workflow:
    name: iOS Build and Deploy v1.0.0
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      xcode: 15.0.1
      node: 20
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        APP_VERSION: "1.0.0"
        BUNDLE_ID: "tech.erconsulting.cinemind.app"
        DEVELOPMENT_TEAM: "WJMVGC7L35"
      groups:
        - app_store_credentials
    scripts:
      - name: Check Node.js version
        script: |
          echo "Node.js version:"
          node --version
          echo "Required: >=20.0.0"
          
      - name: Install dependencies
        script: |
          npm ci
          
      - name: Build web assets
        script: |
          npm run build
          
      - name: Sync Capacitor
        script: |
          npx cap sync ios
          
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install --repo-update
          cd ../..
          
          
      - name: Set up provisioning profiles
        script: |
          echo "=== Setting up provisioning profiles ==="
          xcode-project use-profiles
          
          # List available provisioning profiles
          echo "=== Available Provisioning Profiles ==="
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/ || echo "No profiles in default location"
          
          # Check what profiles are available
          find ~/Library -name "*.mobileprovision" -exec basename {} \; 2>/dev/null || echo "No profiles found"
          
          echo "✓ Provisioning profiles setup completed"
          
      - name: Build iOS app
        script: |
          # Create export options plist with provisioning profile
          cat > "$HOME/export_options.plist" << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>$BUNDLE_ID</key>
                  <string>CineMind App Store distribution</string>
              </dict>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <false/>
              <key>teamID</key>
              <string>$DEVELOPMENT_TEAM</string>
          </dict>
          </plist>
          EOF
          
          # Try xcode-project first, fallback to xcodebuild if it fails
          echo "=== Attempting xcode-project build-ipa ==="
          if xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist "$HOME/export_options.plist" \
            --development-team "$DEVELOPMENT_TEAM"; then
            echo "✓ xcode-project build successful"
          else
            echo "⚠️ xcode-project failed, trying xcodebuild..."
            
            # Fallback to xcodebuild with automatic signing
            xcodebuild \
              -workspace "$XCODE_WORKSPACE" \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -archivePath "$HOME/Library/Developer/Xcode/Archives/App.xcarchive" \
              archive \
              CODE_SIGN_STYLE=Automatic \
              DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
              -allowProvisioningUpdates
            
            # Export IPA
            xcodebuild \
              -exportArchive \
              -archivePath "$HOME/Library/Developer/Xcode/Archives/App.xcarchive" \
              -exportPath "$CM_BUILD_DIR/ios" \
              -exportOptionsPlist "$HOME/export_options.plist"
          fi
          
      - name: Debug App Store Connect credentials
        script: |
          echo "=== App Store Connect Credentials Debug ==="
          echo "Key ID length: ${#APP_STORE_CONNECT_KEY_ID}"
          echo "Issuer ID length: ${#APP_STORE_CONNECT_ISSUER_ID}"
          echo "Private Key length: ${#APP_STORE_CONNECT_PRIVATE_KEY}"
          echo "Key ID starts with: ${APP_STORE_CONNECT_KEY_ID:0:10}..."
          echo "Issuer ID starts with: ${APP_STORE_CONNECT_ISSUER_ID:0:10}..."
          echo "Private Key starts with: ${APP_STORE_CONNECT_PRIVATE_KEY:0:50}..."
          echo "=== Credentials Debug Complete ==="
          
    artifacts:
      - ios/*.ipa
      - ios/*.dSYM.zip
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      
    publishing:
      app_store_connect:
        submit_to_testflight: true
        beta_groups:
          - testers
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
