// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const authOptions = {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
};

/** Config endpoint when no env vars are set: app fetches URL + anon key from Supabase (no host env needed). */
const FALLBACK_CONFIG_URL = "https://vkeurtlppyytdhyknqpx.supabase.co/functions/v1/public-config";

/** Only use env URL if it points at this project (where functions and auth live). */
const CORRECT_PROJECT_REF = "vkeurtlppyytdhyknqpx";

let _client: SupabaseClient<Database> | null = null;

/**
 * Initialize Supabase client. Call once before rendering the app.
 * - If VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY are set and URL is the correct project, uses them.
 * - Else fetches URL + anon key from public-config (no host env needed).
 */
export async function initSupabase(): Promise<SupabaseClient<Database>> {
  if (_client) return _client;

  const url = import.meta.env.VITE_SUPABASE_URL as string | undefined;
  const key = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

  const useEnv = url && key && url.includes(CORRECT_PROJECT_REF);
  if (useEnv) {
    _client = createClient<Database>(url, key, authOptions);
    return _client;
  }

  const res = await fetch(FALLBACK_CONFIG_URL);
  if (!res.ok) throw new Error(`Failed to load config from Supabase (${res.status}). Check that public-config is deployed and SUPABASE_URL/SUPABASE_ANON_KEY are set in Edge Function secrets.`);
  const { supabaseUrl, supabaseAnonKey } = await res.json();
  if (!supabaseUrl || !supabaseAnonKey) throw new Error("Invalid config from Supabase");
  if (!supabaseUrl.includes(CORRECT_PROJECT_REF)) throw new Error(`Config returned wrong project. Expected ${CORRECT_PROJECT_REF}.`);
  _client = createClient<Database>(supabaseUrl, supabaseAnonKey, authOptions);
  return _client;
}

/**
 * Use after initSupabase() has been awaited. Throws if called before init.
 */
function getSupabase(): SupabaseClient<Database> {
  if (!_client) throw new Error("Supabase not initialized. Await initSupabase() before using supabase.");
  return _client;
}

// Same client is used for auth and Edge Functions (movie-identify, etc.); URL is set only in initSupabase.
export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_, prop) {
    return (getSupabase() as any)[prop];
  },
});
